- static/js/api.js
- static/js/index.js
- add alert in api.js, specifically writeReviewAPI
> :ambulance:HOTFIX: update writeReviewAPI #5

- static/js/cart.js
- static/js/ordercheck.js
- change tostring
- change src url form
> :hammer:Refact: refactoring cart js #6

- static/js/chatindex.js
> :sparkles:Feat:limit of creating chatrooms #43

- bill.html
- bill_detail.html
- ordercheck.html
- productdetail.html
- static/css/bill.css
- static/css/bill_detail.css
- static/css/cart.css
- static/css/ordercheck.css
- static/css/productdetail.css
- static/js/api.js
- static/js/bill.js
- static/js/bill_detail.js
- static/js/cart.js
- static/js/ordercheck.js
- static/js/productdetail.js
✨Feat: Add delivery from ordercheck #16
> ✨Feat: Add Bill to Cart, Order to Cart, Add delivery from ordercheck #6 #16

- cart.html
- seller.html
- static/css/writereview.css
- static/js/api.js
- static/js/mypage.js
- static/js/productregistration.js
- static/js/writereview.js
- writereview.html
- add prview in review
- add tolocalstring in mypage points
> :sparkles:Feat: add preview in review #5

- static/css/index.css
- static/js/api.js
- static/js/bill_detail.js
- 구매확정되면 리뷰쓰기버튼생성
- index css 수정
> :sparkles:Feat:  write review only after confirming bills #15

- index.html
- mypage.html
- seller.html
- seller_orderlist.html
- seller_productlist.html
- static/css/footer.css
- static/css/seller_list.css
- static/js/ordercheck.js
- static/js/seller.js
- static/js/seller_list.js
-add modal in seller_orderlist.html
-CSS modify in seller&footer&index&mypage
> :sparkles:Feat: add modal for seller #16

- README.md
- index.html
- static/css/index.css
- static/js/index.js
> :ambulance:HOTFIX: add cursor pointer #1

- chatindex.html
- mypage.html
- static/css/chatindex.css
- static/css/chatroom.css
- static/css/index.css
- static/css/mypage.css
- static/js/api.js
- static/js/chatindex.js
- static/js/ordercheck.js
- tooltip 추가
- 채팅 css (너비 수정)
- 채팅 js 추가 (삭제할 때 접속유저있으면 안되게, 생성할 때 안내문 추가)
> :sparkles:Feat:add tooltip and develop chat css and js #2 #43

- chatroom.html
- pointcharge.html
- static/css/mypage.css
- static/css/pointcharge.css
- static/css/sellerpage.css
- static/js/api.js
- static/js/chatroom.js
- static/js/index.js
> :sparkles:Feat:add tooltip and upgrade chat's room #4 #43

- index.html
- mobile-index.html
- mobile-mypage.html
- mypage.html
- myreview.html
- static/css/index.css
- static/css/mobile-index.css
- static/css/mobile-mypage.css
- static/css/myreview.css
- static/css/pointcharge.css
- static/css/subscription.css
- static/js/api.js
- static/js/mobile-index.js
- static/js/switch-content.js
- 마이페이지
- 내리뷰보기
- 포인트충전
- 메인화면
프론트 모바일 반영했습니다.
> :sparkles:Feat:add mobile front #1 #2 #4 #5

- cbti.html
- static/css/productregistration.css
- static/js/cbti.js
- update cbti.html
- update cbti.js
- check the radio button to advance the slide
>  :sparkles:Feat: update CBTI #114

- index.html
- productregistration.html
- static/css/cbti.css
- static/css/productregistration.css
- static/js/index.js
- update productregistration.html It's not annoying anymore
- update productregistration.css
> :sparkles:Feat: update productregistration files #19

- static/css/productregistration.css
- static/css/sellerpage.css
> :ambulance:HOTFIX: update editbutton in productregistration.css #19

- seller.html
- seller_orderlist.html
- seller_productlist.html
- static/css/productregistration.css
- static/css/seller.css
- static/css/seller_list.css
- update seller.html
- update seller_orderlist.html
- update seller_product.html
> :sparkles:Feat: apply seller.png to sellerpage #19

- static/css/cbti.css
> :ambulance:HOTFIX: apply cbti css #114

- static/css/cbti.css
> :ambulance:HOTFIX: fix cbti css #16

- static/js/cbti.js
> :ambulance:HOTFIX: fix cbti.js #114

- cbti.html
- chatindex.html
- seller.html
- seller_orderlist.html
- seller_productlist.html
- static/css/seller_list.css
- static/js/api.js
- static/js/seller.js
- static/js/seller_list.js
- fix CSS in seller
- add sort in seller
- add link to product detail in seller
- replace chat with under maintenance
> :sparkles:Feat: sort list about seller #16 #43

- static/js/user_detail_page.js
- fix url of seller_img in user_defail_page.js
> :ambulance:HOTFIX: fix url of seller_img #3

- static/css/chatindex.css
> :hammer:Refact: add chat index css for mobile #43

- static/js/api.js
- static/js/index.js
- delete keywordSearchView
- add ordering in index.js now you can find products by registration order but the feature needs some help.
> :sparkles:Feat: add ordering and keyword searching #1

- static/js/api.js
- static/js/index.js
- merge some functions in index.js
> :sparkles:Feat: refoctor codes in index.js #1
